I will now work on problem 2.44 from Taylor, where we're given a drag force that depends on height due to variations in air density in the atmosphere do to height. Here we have the drag force $f(v, y) = \gamma D^2 e^{-y/\lambda}v^2$, $\lambda \approx 10,000$ m. The diameter of the cannonball is $D = 0.15 m$, its density is $7.8 \text{ g/cm}^3$, $\gamma = 0.25 \text{ Ns}^2/\text{m}^4$. 

The equations of motion are: 

\begin{align*}
m \dot{\mathbf{v}} &= m\mathbf{g} - \gamma D^2 e^{-y/\lambda}v^2 \hat{\mathbf{v}} \\
&= m\mathbf{g} - \gamma D^2 e^{-y/\lambda}v \mathbf{v}
\end{align*}

It follows that  

\begin{align*}
m \dot{v}_x &= - \gamma D^2 e^{-y/ \lambda}v v_x \\
m \dot{v}_y &= -mg - \gamma D^2 e^{-y/ \lambda}v v_y
\end{align*}

To solve this, we will follow a similar method as above, letting the state function 

\begin{align*}
\mathbf{f}(\dot{x}, \dot{y}, y, t) = 
\begin{bmatrix}
\ddot{x}(\dot{x}, \dot{y}, y, t) \\
\ddot{y}(\dot{x}, \dot{y}, y, t)
\end{bmatrix}
=
\begin{bmatrix}
-\frac{\gamma}{m} D^2 e^{-y/ \lambda} \sqrt{\dot{x}^2+\dot{y}^2} \dot{x} \\
-g -\frac{\gamma}{m} D^2 e^{-y/ \lambda}\sqrt{\dot{x}^2+\dot{y}^2} \dot{y}
\end{bmatrix}
\end{align*}

Here we will be expressing the velocities in terms of the launch angle $\theta$ and a velocity $v$. Where $v_x = v \cos \theta$ and $v_y = v \sin \theta$.

In [ ]:
import numpy as np
import sympy as sp
import scipy as sc
import matplotlib.pyplot as plt
import ipywidgets as wd
import matplotlib.animation as animation
%matplotlib widget

def rk4(A, B, q0, t, h, params):

    #this function will determine the solution to the 
    #equation given by the state vector above
    g, beta, lam = params
    
    #for q, rows are the x, vx, y, vy; cols are these at 
    #subsequent time steps
    q = np.zeros(len(B), len(t)) #length of B sets dimension of the system
    q[:, 0] = q0 #set the initial conditions
    G = -g*np.array([0,0,0,1])
    x, vx, y, vy = q0


    for i in range(len(t)-1):

        k1 = A @ q[:, i] + B*gamma(params[0], q[0,i], t) + G
        y1 = q[:, i] + k1*h/2

        k2 = A @ y1 + B*gamma(params[0], q[0,i], t) + G
        y2 = q[:, i] + k2*h/2

        k3 = A @ y2 + B*gamma(params[0], q[0,i], t) + G
        y3 = q[:, i] + k3*h

        k4 = A @ y3 + B*gamma(params[0], q[0,i], t) + G
        q[:, i+1] = q[:, i] + (k1 + 2*k2 + 2*k3 + k4)*h/6
    return q


In [24]:
arr = np.array([[1,2,3], 
          [4,5,6],
          [7,8,9], 
          [10,11,12]])

print(arr)
print(arr[:,0])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  4  7 10]
